### ISSUE TITLE
v2.0.0 release checklist

### ISSUE THREAD

**Issue by jgravois** [terraformer-js/terraformer#28]
inspiration - https://github.com/zakjan/leaflet-lasso/issues/10

- [x] ensure tree shaking works
- [x] ~~`export createCircle()`~~
- [x] fix the test suite
- [x] generate/test a flat ESM build
- [x] ensure ESM code is included in bundles
- [x] test CJS syntax
- [x] fix browser tests
- [x] JSDoc > README API Reference
- [x] are arrow functions going to be problematic somehow? 🤷 
- [x] read up on lerna commands for publishing

maybe
- [ ] https://github.com/Esri/terraformer/issues/313
- [ ] https://github.com/Esri/terraformer/issues/321
